<?php
/**
 * @file
 */

use Drupal\content_moderation\Entity\ModerationState;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;


/**
 * Implements hook_entity_operation().
 */
function content_moderation_actions_entity_operation(EntityInterface $entity) {
  $operations = [];
  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderation_information */
  $moderation_information = \Drupal::service('content_moderation.moderation_information');
  if (!$moderation_information->isModeratedEntity($entity)) {
    return $operations;
  }

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $moderation_information->getLatestRevision($entity->getEntityTypeId(), $entity->id());

  /** @var \Drupal\content_moderation\StateTransitionValidation $transition_validation */
  $transition_validation = \Drupal::service('content_moderation.state_transition_validation');
  $states = $transition_validation->getValidTransitionTargets($entity, \Drupal::currentUser());

  /** @var \Drupal\Core\Render\RendererInterface $renderer */
  $renderer = \Drupal::service('renderer');
  $build = [
    '#attached' => [
      'library' => [
        'content_moderation_actions/ajax_commands',
      ],
    ],
  ];
  $renderer->render($build);

  $operations = array_map(function (ModerationState $state) use ($entity) {
    $url = Url::fromRoute('content_moderation_actions.state_change', [
      'entity_type_id' => $entity->getEntityTypeId(),
      'entity_id' => $entity->id(),
      'from' => $entity->get('moderation_state')->target_id,
      'to' => $state->id(),
    ]);

    $operation = [
      'title' => t('Set to @state_label', [
        '@state_label' => $state->label(),
      ]),
      'url' => $url,
      'attributes' => [
        'class' => ['use-ajax'],
      ],
      'weight' => 20,
    ];
    return $operation;
  }, $states);
  return $operations;
}
